services:
  
  interprep-app:
    
    build:

      context: .
      
      dockerfile: Dockerfile
      
      args:
        NEXT_PUBLIC_CONVEX_URL: ${NEXT_PUBLIC_CONVEX_URL}
        NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
        NEXT_PUBLIC_STREAM_API_KEY: ${NEXT_PUBLIC_STREAM_API_KEY}
    
    stdin_open: true
    tty: true

    env_file:
      - .env

    environment:
      NODE_ENV: development
      CLERK_SECRET_KEY: ${CLERK_SECRET_KEY}
      STREAM_SECRET_KEY: ${STREAM_SECRET_KEY}
      CLERK_WEBHOOK_SECRET: ${CLERK_WEBHOOK_SECRET}
      CONVEX_DEPLOYMENT: ${CONVEX_DEPLOYMENT}
      
    ports:
      - "3000:3000"
      - "4000:4000"

    volumes:
      - .:/app
      - /app/node_modules

    working_dir: /app

    command: >
      sh -c "npx convex dev & npm run dev"


