name: Integration

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:  
    runs-on: ubuntu-latest

  strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

  env:
    NEXT_PUBLIC_CONVEX_URL: ${{ secrets.NEXT_PUBLIC_CONVEX_URL }}
    NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
    NEXT_PUBLIC_STREAM_API_KEY: ${{ secrets.NEXT_PUBLIC_STREAM_API_KEY }}
    CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
    STREAM_SECRET_KEY: ${{ secrets.STREAM_SECRET_KEY }}
    CLERK_WEBHOOK_SECRET: ${{ secrets.CLERK_WEBHOOK_SECRET }}
    CONVEX_DEPLOYMENT: ${{ secrets.CONVEX_DEPLOYMENT }}
  
  steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

      - name: "Installing Dependencies"
        run: npm ci

      - name: "Build Next.js app"
        run: npm run build